import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import Footer from "@components/Footer";
import Header from "@components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} h-screen max-h-screen overflow-hidden`}>
        <div className="grid grid-rows-[50px_1fr_30px] h-screen max-h-screen overflow-hidden">
          <header className="flex items-center justify-center">
            <Header />
          </header>
          <div className="overflow-auto bg-neutral-100">
            {children}
          </div>
          <footer
            className="w-full h-full flex items-center justify-center text-sm text-gray-500"
            tabIndex={0}
            aria-label="Footer"
          >
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
